### ISSUE TITLE
Bug in forum

### ISSUE THREAD

**Issue by dguprado** [slawkens/myaac#241] opened 2023-12-09 01:03 UTC
I create a new board in the forum and all replies are shown with the name of the board author.
i am running a canary server 3.1.2 on windows server 2012

i am using the last rev of myaac from https://my-aac.org/

![bug forum](https://github.com/slawkens/myaac/assets/151960974/1cd5fa7b-e327-4696-91ad-1621015c0a84)

**Comment by slawkens** [comment] 2023-12-09 16:19
I cannot reproduce that. Are you sure you using official version from https://github.com/slawkens/myaac

or maybe you using opentibiabr version as its canary? https://github.com/opentibiabr/myaac

**Comment by slawkens** [comment] 2024-01-18 20:51
I cannot reproduce this. Any tips?

**Comment by dguprado** [comment] 2024-01-19 19:14
This happens when you mix files from your repository with files from the tibiabr repository. I managed to resolve this issue by restoring 90% of my site to your repository. I believe this is a problem related to the tibiabr repository.

**Comment by slawkens** [comment] 2024-01-19 20:07
Ye that sound reasonable. I will close the issue then as its not related to this repo.

Feel free to reopen if you feel the issue exist on my repo.

**Closed** 2024-01-19 20:07 UTC

**Comment by dguprado** [comment] 2024-03-08 04:40
Slawkens How do I install the pagseguro plugin? Do I need to place a file in the htdocs folder for pagseguro to communicate?

**Comment by slawkens** [comment] 2024-03-10 12:17
> Slawkens How do I install the pagseguro plugin? Do I need to place a file in the htdocs folder for pagseguro to communicate?

The pagseguro plugin doesn't work anymore, cause they changed the API.
