### ISSUE TITLE
?account/create

### ISSUE THREAD

**Issue by mlodzian4646** [slawkens/myaac#24] opened 2017-10-22 12:11 UTC
I have a problem when setting up a new account.
The white page with error 500 is displayed

**Comment by slawkens** [comment] 2017-10-22 13:29
Using latest 0.6.5 Version?

Can you post your apache error.log?

**Comment by Riicksouzaa** [comment] 2017-11-27 17:22
see chmod privileges

**Comment by slawkens** [comment] 2017-11-29 07:54
As stated here: https://otland.net/threads/myaac-v0-7-0.251454/page-16#post-2476511

Its probably caused by changing account_premium_days to anything higher than 0.

I will look into this today.

**Comment by slawkens** [comment] 2018-01-04 07:01
This has been fixed in 3e49ef42a2d9e0b8e2f8a76f6eaf2ab035e37876

**Closed by slawkens** 2018-01-04 07:01 UTC
Labels: bug, OTHire
