### ISSUE TITLE
Problem Creating Character

### ISSUE THREAD

**Issue by fernandobahiense** [slawkens/myaac#103] opened 2020-01-21 20:30 UTC
I have found 2 problems in creating character, the first one:

People can create characters with more than 1 space like "Test  test", and despite the site says the character name with monster name is locked, if you proceed creating character it will be created!

Second one: The new account page where is possible to create character in the same page with account, when you finish the account is created but the character don't

**Comment by slawkens** [comment] 2020-01-21 22:50
Hi,

1. Are you sure you are not logged as admin when creating that character?

2. Do you get any error message?

**Comment by fernandobahiense** [comment] 2020-01-22 00:32
I tried you're correct, in others account can't create character with monster name, but it's possible to create with more than 1 space.

2- No errors, it just create account log directly into account and the character list is empty, also the character you tried to create isn't in database

**Comment by Aerwix** [comment] 2020-02-21 03:41
Had the same issue today, after creating account, was impossible to create a character.

Console (f12) said: "$ not defined"

the problem was in the file "check_name.js"

**Comment by slawkens** [comment] 2020-02-28 21:17
> Had the same issue today, after creating account, was impossible to create a character.
> 
> Console (f12) said: "$ not defined"
> 
> the problem was in the file "check_name.js"

I can't reproduce that. Are you using custom template that overrides jQuery?

**Comment by Aerwix** [comment] 2020-03-01 18:17
Nope, i just downloaded and run the 8.0

**Comment by slawkens** [comment] 2020-06-03 19:43
About the second issue: I still can't reproduce that.

Can you provide additional details, like what are you entering into fields, and what your configuration of MyAAC looks like?

**Comment by slawkens** [comment] 2020-08-03 22:53
Closing due no feedback.

**Closed by slawkens** 2020-08-03 22:53 UTC
Labels: bug, help wanted

**Comment by carcoo** [comment] 2021-07-26 11:58
well it is still bugged since 2020, you can't create character while creating account while the checkers work normally, from the create account page, tried with the latest libs and php not working
